# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a373d5127377af77b69ae02d597d27652dd0187c4c7f056a9725bdd2c441df4b59ab169bfa7312d2287e0e003d0b73ba98360d18e7950b784bd7f85561800cd

test:
  secret_key_base: 24cfb0079322d9aa5003cec3c61cd4933c86005f03aa18b5796307578835459fb0e54efe89049afa959d8bf47dd73fcf7cf89e1f8c5d1ea63cd0d55b6529bde9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
