Staff.destroy_all
Office.destroy_all
Tool.destroy_all
Skillset.destroy_all
Project.destroy_all

o1 = Office.create(:location => 'Chicago', :remote => false)
o2 = Office.create(:location => 'New York', :remote => false)
o3 = Office.create(:location => 'Santa Monica', :remote => false)
o4 = Office.create(:location => 'San Francisco', :remote => false)
o5 = Office.create(:location => 'Washington DC', :remote => false)
o6 = Office.create(:location => 'Asheville, NC', :remote => true)

d1 = Department.create(:name => 'Action Fund', :description => 'This Department does some stuff...')
d2 = Department.create(:name => 'Center for Market Innovation', :description => 'This Department does some stuff...')
d3 = Department.create(:name => 'Center For Policy Advocacy', :description => 'This Department does some stuff...')
d4 = Department.create(:name => 'China', :description => 'This Department does some stuff...')
d5 = Department.create(:name => 'Climate & Clean Air', :description => 'This Department does some stuff...')
d6 = Department.create(:name => 'Communications', :description => 'This Department does some stuff...')
d7 = Department.create(:name => 'Development', :description => 'This Department does some stuff...')
d8 = Department.create(:name => 'E2', :description => 'This Department does some stuff...')
d9 = Department.create(:name => 'Energy & Transportation', :description => 'This Department does some stuff...')
d10 = Department.create(:name => 'Facilities', :description => 'This Department does some stuff...')
d11 = Department.create(:name => 'Finance', :description => 'This Department does some stuff...')
d12 = Department.create(:name => 'Food & Agriculture', :description => 'This Department does some stuff...')
d13 = Department.create(:name => 'Health', :description => 'This Department does some stuff...')
d14 = Department.create(:name => 'HR', :description => 'This Department does some stuff...')
d15 = Department.create(:name => 'International', :description => 'This Department does some stuff...')
d16 = Department.create(:name => 'IT', :description => 'This Department does some stuff...')
d17 = Department.create(:name => 'Land & Wildlife', :description => 'This Department does some stuff...')
d18 = Department.create(:name => 'Litigation', :description => 'This Department does some stuff...')
d19 = Department.create(:name => 'Midwest Regional', :description => 'This Department does some stuff...')
d20 = Department.create(:name => 'New York (Program)', :description => 'This Department does some stuff...')
d21 = Department.create(:name => 'Oceans', :description => 'This Department does some stuff...')
d22 = Department.create(:name => 'Science Center', :description => 'This Department does some stuff...')
d23 = Department.create(:name => 'Urban Solutions', :description => 'This Department does some stuff...')
d24 = Department.create(:name => 'Water', :description => 'This Department does some stuff...')

s1 = Staff.create(:name_first => 'Jay', :name_last => 'Orfield', :email => 'jorfield@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o2.id, :department_id => d9.id)
s2 = Staff.create(:name_first => 'Nathanael', :name_last => 'Greene', :email => 'ngreene@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o2.id, :department_id => d9.id)
s3 = Staff.create(:name_first => 'Lara', :name_last => 'Ettenson', :email => 'lettenson@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o4.id, :department_id => d9.id)
s4 = Staff.create(:name_first => 'Sarah', :name_last => 'Dougherty', :email => 'sdougherty@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o5.id, :department_id => d2.id)
s5 = Staff.create(:name_first => 'Lauren', :name_last => 'Zullo', :email => 'lzullo@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o1.id, :department_id => d23.id)
s6 = Staff.create(:name_first => 'Kimiko', :name_last => 'Martinez', :email => 'kmartinez@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o3.id, :department_id => d6.id)
s7 = Staff.create(:name_first => 'Luis', :name_last => 'Martinez', :email => 'lmartinez@nrdc.org', :password => '1234NRDC', :password_confirmation => '1234NRDC', :office_id => o6.id, :department_id => d9.id)

t1 = Tool.create(:name => 'Excel')
t2 = Tool.create(:name => 'Outlook')
t3 = Tool.create(:name => 'PowerPoint')
t4 = Tool.create(:name => 'Word')

sk1 = Skillset.create(:staff_id => s1.id, :tool_id => t1.id, :proficiency => 'Novice')
sk2 = Skillset.create(:staff_id => s1.id, :tool_id => t2.id, :proficiency => 'Competent')
sk3 = Skillset.create(:staff_id => s1.id, :tool_id => t3.id, :proficiency => 'Experienced')
sk4 = Skillset.create(:staff_id => s2.id, :tool_id => t2.id, :proficiency => 'Expert')
sk5 = Skillset.create(:staff_id => s2.id, :tool_id => t3.id, :proficiency => 'Novice')
sk6 = Skillset.create(:staff_id => s2.id, :tool_id => t4.id, :proficiency => 'Competent')
sk7 = Skillset.create(:staff_id => s3.id, :tool_id => t3.id, :proficiency => 'Experienced')
sk8 = Skillset.create(:staff_id => s3.id, :tool_id => t4.id, :proficiency => 'Expert')
sk9 = Skillset.create(:staff_id => s3.id, :tool_id => t1.id, :proficiency => 'Novice')
sk10 = Skillset.create(:staff_id => s4.id, :tool_id => t4.id, :proficiency => 'Competent')
sk11 = Skillset.create(:staff_id => s4.id, :tool_id => t1.id, :proficiency => 'Experienced')
sk12 = Skillset.create(:staff_id => s4.id, :tool_id => t2.id, :proficiency => 'Expert')

p1 = Project.create(:name => 'Project #1', :description => 'This Project belongs to...')
p2 = Project.create(:name => 'Project #2', :description => 'This Project belongs to...')
p3 = Project.create(:name => 'Project #3', :description => 'This Project belongs to...')
p4 = Project.create(:name => 'Project #4', :description => 'This Project belongs to...')
p5 = Project.create(:name => 'Project #5', :description => 'This Project belongs to...')
p6 = Project.create(:name => 'Project #6', :description => 'This Project belongs to...')
p7 = Project.create(:name => 'Project #7', :description => 'This Project belongs to...')
p8 = Project.create(:name => 'Project #8', :description => 'This Project belongs to...')